import express from 'express';
import multer from 'multer';
const app=express(),upload=multer({storage:multer.memoryStorage(),limits:{fileSize:8*1024*1024},fileFilter:(req,file,cb)=>cb(null,/^image\/(jpeg|png|webp|gif)$/.test(file.mimetype))});app.use(express.json());app.use(express.static('public'));
const feeRate=Number(process.env.MARKETPLACE_FEE_RATE||.12),plusPrice=Number(process.env.PLUS_MONTHLY_PRICE||9.99);
const state={user:{id:'beta',name:'IDLE Beta Tester',plan:'free',scans:0},assets:[],listings:[{id:'l1',title:'DeWalt Pressure Washer',category:'Tools',rate:49,deposit:75,distance:'3.2 mi',rating:4.9},{id:'l2',title:'JBL PartyBox',category:'Event Gear',rate:55,deposit:100,distance:'5.1 mi',rating:4.8},{id:'l3',title:'Sony Alpha Camera Kit',category:'Photography',rate:68,deposit:150,distance:'7.4 mi',rating:5}],bookings:[]};
const money=n=>Math.round(Number(n)*100)/100;const quote=(rate,days,deposit=0)=>{const rental=money(rate*days),fee=money(rental*feeRate);return{rental,fee,deposit:Number(deposit),charge:money(rental+fee),ownerPayout:rental}};
const clamp=(n,min,max)=>Math.max(min,Math.min(max,Number(n)||0));
function scoreAsset(x){const s=x.scoreFactors||{};return Math.round(clamp(s.rentalDemand,0,100)*.25+clamp(s.monthlyRevenue,0,100)*.20+clamp(s.resaleStrength,0,100)*.15+clamp(s.utilization,0,100)*.15+clamp(s.seasonality,0,100)*.10+clamp(s.lowRisk,0,100)*.10+clamp(s.lowEffort,0,100)*.05)}
async function analyzePhoto(file){if(!process.env.OPENAI_API_KEY)throw new Error('AI scanner is not configured');const dataUrl=`data:${file.mimetype};base64,${file.buffer.toString('base64')}`;const schema={type:'object',additionalProperties:false,properties:{title:{type:'string'},category:{type:'string'},brand:{type:'string'},model:{type:'string'},confidence:{type:'number'},resaleLow:{type:'number'},resaleHigh:{type:'number'},rentalLow:{type:'number'},rentalHigh:{type:'number'},suggestedRate:{type:'number'},monthlyOpportunity:{type:'number'},recommendation:{type:'string',enum:['RENT','SELL','TRADE','PROTECT','KEEP']},evidence:{type:'array',items:{type:'string'},minItems:3,maxItems:5},scoreFactors:{type:'object',additionalProperties:false,properties:{rentalDemand:{type:'number'},monthlyRevenue:{type:'number'},resaleStrength:{type:'number'},utilization:{type:'number'},seasonality:{type:'number'},lowRisk:{type:'number'},lowEffort:{type:'number'}},required:['rentalDemand','monthlyRevenue','resaleStrength','utilization','seasonality','lowRisk','lowEffort']}},required:['title','category','brand','model','confidence','resaleLow','resaleHigh','rentalLow','rentalHigh','suggestedRate','monthlyOpportunity','recommendation','evidence','scoreFactors']};const resp=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${process.env.OPENAI_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({model:'gpt-5-mini',input:[{role:'system',content:[{type:'input_text',text:'You are IDLE asset intelligence. Identify the main physical item in the photo. Give conservative US-dollar estimates for used resale value and plausible peer-to-peer daily rental value. These are estimates, not live marketplace comps. If brand/model is uncertain say Unknown and lower confidence. Score each factor 0-100. Evidence must briefly state what is visible and that values are estimates.'}]},{role:'user',content:[{type:'input_text',text:'Analyze this item for IDLE. Return only the requested structured data.'},{type:'input_image',image_url:dataUrl}]}],text:{format:{type:'json_schema',name:'idle_asset_analysis',strict:true,schema}}})});const body=await resp.json();if(!resp.ok)throw new Error(body?.error?.message||'OpenAI scan failed');const txt=body.output?.flatMap(o=>o.content||[]).find(c=>c.type==='output_text')?.text;if(!txt)throw new Error('No analysis returned');return JSON.parse(txt)}
app.get('/api/health',(q,r)=>r.json({ok:true,version:'1.10.0',mode:process.env.OPENAI_API_KEY?'vision-enabled':'vision-unconfigured'}));
app.get('/api/bootstrap',(q,r)=>r.json({user:state.user,assets:state.assets,listings:state.listings,plusPrice,feeRate}));
app.post('/api/scan',upload.single('photo'),async(q,r)=>{if(!q.file)return r.status(400).json({error:'A JPG, PNG, WEBP or GIF photo under 8 MB is required.'});try{state.user.scans++;const x=await analyzePhoto(q.file),idleScore=scoreAsset(x);r.json({mode:'AI estimate',identity:{title:x.title,category:x.category,brand:x.brand,model:x.model,confidence:clamp(x.confidence,0,1)},valuation:{resaleLow:money(x.resaleLow),resaleHigh:money(x.resaleHigh),rentalLow:money(x.rentalLow),rentalHigh:money(x.rentalHigh),suggestedRate:money(x.suggestedRate)},monthlyOpportunity:money(x.monthlyOpportunity),idleScore,recommendation:x.recommendation,evidence:x.evidence})}catch(e){console.error('scan error',e.message);r.status(502).json({error:'IDLE could not analyze that photo. Please try a clearer photo.',detail:process.env.NODE_ENV==='development'?e.message:undefined})}});
app.get('/api/listings',(q,r)=>{const s=String(q.query.q||'').toLowerCase();r.json(state.listings.filter(x=>!s||(`${x.title} ${x.category}`).toLowerCase().includes(s)))});
app.post('/api/bookings/quote',(q,r)=>r.json(quote(Number(q.body.rate),Math.max(1,Number(q.body.days)),Number(q.body.deposit))));
app.post('/api/bookings',(q,r)=>{const l=state.listings.find(x=>x.id===q.body.listingId);if(!l)return r.status(404).json({error:'Listing not found'});const b={id:'bk'+Date.now(),listingId:l.id,title:l.title,status:'requested',pricing:quote(l.rate,Math.max(1,Number(q.body.days)),l.deposit)};state.bookings.push(b);r.json(b)});app.get('/api/bookings',(q,r)=>r.json(state.bookings));
app.post('/api/plus',(q,r)=>{state.user.plan='plus';r.json(state.user)});
app.listen(Number(process.env.PORT)||8787,()=>console.log('IDLE private beta running'));